import turtle

turtle.shape('turtle')
turtle.up()
turtle.goto(0, 0)
turtle.left(90)
turtle.down()
turtle.color('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.up()
turtle.goto(-120, 50)
turtle.down()
turtle.color('blue')
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.up()
turtle.goto(-30, 50)
turtle.down()
turtle.color('blue')
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.up()
turtle.goto(-95, 30)
turtle.down()
turtle.color('black')
turtle.pensize(8)
turtle.left(180)
turtle.forward(50)
turtle.up()
turtle.goto(-30, -10)
turtle.color('red')
turtle.down()
turtle.circle(-70, 180, 30)
print()
